name: Build and Deploy Angular App to FTP

on:
  push:
    branches:
      - main # Trigger on push to the main branch, change as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tipovacka-app'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Set this to your Node.js version
          cache: 'yarn'  # Enable Yarn caching
          cache-dependency-path: ./tipovacka-app/yarn.lock

      - name: Install Angular CLI
        run: yarn global add @angular/cli

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Build Angular App
        run: yarn ng build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 336374.w74.wedos.net
          username: w336374
          password: nrvRUPG3
          local-dir: ./tipovacka-app/dist/ # Adjust if your build output path is different
          server-dir: /www/subdom/football/
