name: ESLint

on:
  pull_request:

jobs:
  ESLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tipovacka-app'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Set this to your Node.js version

      - name: Install ESLint
        run: yarn add eslint

      - name: Run ESLint
        run: yarn lint